### PR TITLE
Theoyeah_logo in the intro

### PR DESCRIPTION
**Pull request by Wither362**
Yeah, Theoyeah logo appears in the intro, I don’t know the size, so if you could do it for me, I would be very appreciated

### CODE REVIEW

**Comment by Theoyeah** [comment]
The size is 125 x 125 or smth

**Comment by Wither362** [comment]
Ok

**Comment by Theoyeah** [comment]
Oh sh*t something got fucked

**Comment by Theoyeah** [comment]
You can merge it when it is fixed

**Comment by Wither362** [comment]
Ok

**Comment by Theoyeah** [comment]
Ok gonna merge, it works

**Pull request merged**
