### PR TITLE
Crash note

### PR DESCRIPTION
**Pull request by Wither362**
It’s only to see if this note works, no matter if you don’t want this, it’s only for _me_ to prove it, and **don’t** merge it **without** my permission please ;)

### CODE REVIEW

**Comment by Wither362** [comment]
> Okay, now this should work, just needs testing

You are in windows or linux or Mac?

**Comment by Wither362** [comment]
> > > Okay, now this should work, just needs testing
> > 
> > 
> > You are in windows or linux or Mac?
> 
> I just did all the code on an iPad, but, I mostly do my coding on Windows

That means you’ll have to wait 30 minutes to compile (windows is 30 minutes, linux is 16 minutes, and Mac is 16-30 minutes)

**Comment by DEMOLITIONDON96** [comment]
> > > > Okay, now this should work, just needs testing
> > > 
> > > 
> > > You are in windows or linux or Mac?
> > 
> > 
> > I just did all the code on an iPad, but, I mostly do my coding on Windows
> 
> That means you’ll have to wait 30 minutes to compile (windows is 30 minutes, linux is 16 minutes, and Mac is 16-30 minutes)

Yup :’)

**Comment by Theoyeah** [comment]
@DEMOLITIONDON96 did you fix poison note not doing the effect ? i took out from chartingstate

**Comment by Theoyeah** [comment]
Bro 4.0 gonna be huge

**Comment by DEMOLITIONDON96** [comment]
> @DEMOLITIONDON96 did you fix poison note not doing the effect ? i took out from chartingstate

Fuck it, i’mma just replace it with the code from my engine, cause that one is working

**Comment by Theoyeah** [comment]
> > @DEMOLITIONDON96 did you fix poison note not doing the effect ? i took out from chartingstate
> 
> Fuck it, i’mma just replace it with the code from my engine, cause that one is working

ok

**Comment by DEMOLITIONDON96** [comment]
> > > @DEMOLITIONDON96 did you fix poison note not doing the effect ? i took out from chartingstate
> > 
> > 
> > Fuck it, i’mma just replace it with the code from my engine, cause that one is working
> 
> ok

nvm, the code you have for it is the same, it was just where the code was placed at

**Comment by DEMOLITIONDON96** [comment]
LOL, THE NOTE ACTUALLY CLOSES THE GAME IF YOU TRY TO USE IT IN CHART EDITOR, I think it's because you put it in Note.hx, lemme remove it

**Comment by DEMOLITIONDON96** [comment]
Results: Success

Notes: Mechanic is Fully Functional, Poison Notes didn't get fixed unfortunately, and the only problem I can fix now is the note textures it needs

**Comment by DEMOLITIONDON96** [comment]
okay, now it works, i'm gonna merge this myself in a bit

**Pull request merged**
